# Generated by Django 4.1.7 on 2023-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
                ('age1', models.IntegerField()),
                ('age2', models.IntegerField()),
                ('pet', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
