# Generated by Django 4.1.7 on 2023-10-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellpet',
            old_name='img',
            new_name='image',
        ),
    ]
