# Generated by Django 4.1.7 on 2023-10-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_sellpet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
