# Generated by Django 4.1.7 on 2023-10-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AlterField(
            model_name='sellpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
