# Generated by Django 4.1.7 on 2023-10-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='sellPet',
        ),
    ]
