# Generated by Django 4.1.7 on 2023-10-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selldog',
            old_name='name',
            new_name='username',
        ),
    ]
