# Generated by Django 4.1.7 on 2023-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_selldog_image_selldog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('Siamese cat', 'Siamese cat'), ('Persian cat', 'Persian cat'), ('Somali cat', 'Somali cat'), ('Burmese cat', 'Burmese cat'), ('American bobtail', 'American bobtail')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
