# Generated by Django 4.1.7 on 2023-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sellcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogAccessoriesFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='selldog',
            name='breed',
            field=models.CharField(choices=[('German shephard', 'German shephard'), ('labrador', 'labrador'), ('pug', 'pug'), ('Golden Retriever', 'Golden Retriever'), ('Siberian Husky', 'Siberian Husky'), ('Rottweiler', 'Rottweiler'), ('Bulldog', 'Bulldog'), ('Put Bull', 'Pit Bull'), ('Pomeranian', 'Pomeranian'), ('Basset Hound', 'Basset Hound')], max_length=100),
        ),
    ]
