# Generated by Django 4.1.7 on 2023-10-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_dogaccessoriesfood_alter_selldog_breed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dogAccessoriesFood',
        ),
    ]
