# Generated by Django 4.1.7 on 2023-10-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_dogaccessoriesfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
