# Generated by Django 4.1.7 on 2023-10-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_dogfood_productname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dogFood',
            new_name='foodDog',
        ),
    ]
