# Generated by Django 4.1.7 on 2023-10-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_dogfood_fooddog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodDog',
            new_name='dogFood',
        ),
    ]
