# Generated by Django 4.1.7 on 2023-10-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_fooddog_dogfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dogToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
