# Generated by Django 4.1.7 on 2023-10-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_doctor_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
