# Generated by Django 4.1.7 on 2023-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('address', models.TextField(blank=True, max_length=300)),
                ('pet', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=300)),
            ],
        ),
    ]
