# Generated by Django 4.1.7 on 2023-10-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date',
        ),
    ]
