# Generated by Django 4.1.7 on 2023-10-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_feedback_alter_doctor_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedbackone',
        ),
    ]
