# Generated by Django 4.1.7 on 2023-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_feedback_feedbackone'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('Siamese cat', 'Siamese cat'), ('Persian cat', 'Persian cat'), ('Somali cat', 'Somali cat'), ('Burmese cat', 'Burmese cat'), ('American bobtail', 'American bobtail')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trackDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('German shephard', 'German shephard'), ('labrador', 'labrador'), ('pug', 'pug'), ('Golden Retriever', 'Golden Retriever'), ('Siberian Husky', 'Siberian Husky'), ('Rottweiler', 'Rottweiler'), ('Bulldog', 'Bulldog'), ('Put Bull', 'Pit Bull'), ('Pomeranian', 'Pomeranian'), ('Basset Hound', 'Basset Hound')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
